### PR TITLE
Missing index with SQLite

### PR DESCRIPTION
**Pull request by pnax**
## Purpose

This PR creates indexes for the `test_results` table with SQLite.

## Context

This is part 1/11 from #841

## Changes

Create indexes in SQLite.

## How to test this PR

A newly created SQLite database should have indexes `PRAGMA index_info(test_results)`.
Upgrading a database will be done in a later PR.

### CODE REVIEW

**Comment by pnax** [comment]
Well the idea was to split #841 but Travis complains at my first split. I'm giving up on this idea.

**Comment by matsduf** [comment]
The columns in the index must match the columns in the table definition.

**Comment by pnax** [comment]
indeed, I can start again. Thanks for spotting the error.

**Comment by matsduf** [comment]
> indeed, I can start again. Thanks for spotting the error.

Well, Travis told me. :-)

**Comment by pnax** [comment]
Oops I may have been to fast on this one. This should be fixed.

**Review by matsduf — APPROVED** [review]
This works fine. I have not, however, measured if there is any gain.

**Comment by pnax** [comment]
> I have not, however, measured if there is any gain.

This is something I plan to do in a later PR (we've spotted some performance issue in the Backend).

**Pull request merged**
