### PR TITLE
Build against Engine develop branch

### PR DESCRIPTION
**Pull request by mattias-p**
This is an attempt to make Backend run its tests against the Engine develop branch. This is needed as the profiles feature is a breaking change.

### CODE REVIEW

**Comment by matsduf** [comment]
Please provide a description.

Before we merge the profile branch into the develop branch we must do an update of the Travis settings changed by this PR. I suggest that is prepared when this is merged so that it is not forgotten.

**Comment by sandoche2k** [comment]
@matsduf pls. approve

**Comment by matsduf** [comment]
It still fails with Travis.

**Comment by mattias-p** [comment]
@mtoma Could you review this? I've updated this PR so that it tests against the Engine develop branch. It fails now because of the problems in the Backend profiles branch, but I expect this PR will start passing once the Backend profiles problems are fixed. Once this is merged, the Backend profiles branch should start passing as well.

@matsduf Would you consider reviewing dismissing your "requested changes" (or even approving)? Travis is quite capable to speak for itself.

**Comment by mtoma** [comment]
Should be ok now, please restart the Travis test and let me know.
As far as I can see he travis test now hangs on missing features in the engine.

----- Mail original -----
De: "Mattias Päivärinta" <notifications@github.com>
À: "zonemaster/zonemaster-backend" <zonemaster-backend@noreply.github.com>
Cc: "Michal TOMA" <michal.toma@afnic.fr>, "Mention" <mention@noreply.github.com>
Envoyé: Mercredi 9 Janvier 2019 15:08:41
Objet: Re: [zonemaster/zonemaster-backend] Build against Engine develop branch (#463)

@mtoma Could you review this? I've updated this PR so that it tests against the Engine develop branch. It fails now because of the problems in the Backend profiles branch, but I expect this PR will start passing once the Backend profiles problems are fixed. Once this is merged, the Backend profiles branch should start passing as well.

@matsduf Would you consider reviewing dismissing your "requested changes" (or even approving)? Travis is quite capable to speak for itself.

**Comment by sandoche2k** [comment]
@mtoma ... i restarted the build. It still fails : https://travis-ci.org/zonemaster/zonemaster-backend/builds/477353325?utm_source=github_status&utm_medium=notification

**Comment by sandoche2k** [comment]
@matsduf do you agree that @mattias-p merges this PR ?

**Comment by mtoma** [comment]
Can you please retry now after Pierre merged his PR with the API syntax check part?

----- Mail original -----
De: "Mattias Päivärinta" <notifications@github.com>
À: "zonemaster/zonemaster-backend" <zonemaster-backend@noreply.github.com>
Cc: "Michal TOMA" <michal.toma@afnic.fr>, "Mention" <mention@noreply.github.com>
Envoyé: Mercredi 9 Janvier 2019 17:56:19
Objet: Re: [zonemaster/zonemaster-backend] Build against Engine develop branch (#463)

AFAICT now it tests with develop versions of both LDNS and Engine. However there's something else failing.

I'd like to merge this so that the remaining problems can be fixed on the profiles branch. Do you agree that the current failure is related to the Backend code (as opposed to Travis configuration or versions of dependencies)?

**Comment by matsduf** [comment]
It is fine to merge as far as I am concerned.

**Comment by mattias-p** [comment]
The tests seem to pass now, except for one curious error (so far). This is for PostgreSQL and Perl 5.20:
```
$ if [[ "$TARGET" == "PostreSQL" ]]; then perl -I./lib ./t/test_DB_backend.pl PostgreSQL; fi
ok 1 - Testing a supported database backend: PostgreSQL
not ok 2 - use Zonemaster::Backend::RPCAPI;
#   Failed test 'use Zonemaster::Backend::RPCAPI;'
#   at ./t/test_DB_backend.pl line 27.
#     Tried to use 'Zonemaster::Backend::RPCAPI'.
#     Error:  Property net.ipv4 is of type Boolean at /tmp/local-lib-LIBHpF/lib/perl5/Zonemaster/Engine/Profile.pm line 225, <DATA> line 1.
# Compilation failed in require at /tmp/local-lib-LIBHpF/lib/perl5/Zonemaster/Engine.pm line 11, <DATA> line 1.
# BEGIN failed--compilation aborted at /tmp/local-lib-LIBHpF/lib/perl5/Zonemaster/Engine.pm line 11, <DATA> line 1.
# Compilation failed in require at lib/Zonemaster/Backend/RPCAPI.pm line 19, <DATA> line 1.
# BEGIN failed--compilation aborted at lib/Zonemaster/Backend/RPCAPI.pm line 19, <DATA> line 1.
# Compilation failed in require at ./t/test_DB_backend.pl line 27, <DATA> line 1.
# BEGIN failed--compilation aborted at ./t/test_DB_backend.pl line 27, <DATA> line 1.
Can't locate object method "new" via package "Zonemaster::Backend::RPCAPI" at ./t/test_DB_backend.pl line 29, <DATA> line 1.
# Tests were run but no plan was declared and done_testing() was not seen.
# Looks like your test exited with 255 just after 2.
The command "if [[ "$TARGET" == "PostreSQL" ]]; then perl -I./lib ./t/test_DB_backend.pl PostgreSQL; fi" exited with 255.
```
I'm restarting the job to see if the error is intermittent.

**Comment by mattias-p** [comment]
Perl 5.20 with MySQL failed too:
```
$ if [[ "$TARGET" == "MySQL" ]]; then perl -I./lib ./t/test_DB_backend.pl MySQL; fi
ok 1 - Testing a supported database backend: MySQL
not ok 2 - use Zonemaster::Backend::RPCAPI;
#   Failed test 'use Zonemaster::Backend::RPCAPI;'
#   at ./t/test_DB_backend.pl line 27.
#     Tried to use 'Zonemaster::Backend::RPCAPI'.
#     Error:  Property resolver.defaults.fallback is of type Boolean at /tmp/local-lib-BI3Pz1/lib/perl5/Zonemaster/Engine/Profile.pm line 225, <DATA> line 1.
# Compilation failed in require at /tmp/local-lib-BI3Pz1/lib/perl5/Zonemaster/Engine.pm line 11, <DATA> line 1.
# BEGIN failed--compilation aborted at /tmp/local-lib-BI3Pz1/lib/perl5/Zonemaster/Engine.pm line 11, <DATA> line 1.
# Compilation failed in require at lib/Zonemaster/Backend/RPCAPI.pm line 19, <DATA> line 1.
# BEGIN failed--compilation aborted at lib/Zonemaster/Backend/RPCAPI.pm line 19, <DATA> line 1.
# Compilation failed in require at ./t/test_DB_backend.pl line 27, <DATA> line 1.
# BEGIN failed--compilation aborted at ./t/test_DB_backend.pl line 27, <DATA> line 1.
Can't locate object method "new" via package "Zonemaster::Backend::RPCAPI" at ./t/test_DB_backend.pl line 29, <DATA> line 1.
# Tests were run but no plan was declared and done_testing() was not seen.
# Looks like your test exited with 255 just after 2.
The command "if [[ "$TARGET" == "MySQL" ]]; then perl -I./lib ./t/test_DB_backend.pl MySQL; fi" exited with 255.
```
Restarting that as well.

**Comment by mattias-p** [comment]
And finally the SQLite tests fail for all versions of Perl and I'm not bothering to restart them.
```
t/test_validate_syntax.t .. ok
t/test01.t ................ Can't locate object method "config" via package "Zonemaster::Engine" at t/test01.t line 12.
t/test01.t ................ Dubious, test returned 255 (wstat 65280, 0xff00)
No subtests run 
Test Summary Report
-------------------
t/test01.t              (Wstat: 65280 Tests: 0 Failed: 0)
  Non-zero exit status: 255
  Parse errors: No plan found in TAP output
Files=2, Tests=27,  2 wallclock secs ( 0.02 usr  0.02 sys +  1.64 cusr  0.08 csys =  1.76 CPU)
Result: FAIL
The command "if [[ "$TARGET" == "SQLite" ]]; then perl Makefile.PL && make test; fi" exited with 1.
```

**Comment by mattias-p** [comment]
Building against the develop branches of Engine and LDNS seem to work fine now, which is the scope of this PR.
I'm merging this and creating issues for the above problems.

**Pull request merged**
