### PR TITLE
Update installation document

### PR DESCRIPTION
**Pull request by matsduf**
## Purpose

This PR adds a unified structure of the sections and headings, and it makes it easier to install for MariaDB and PostgreSQL by adding initialization scripts.

## Context

* Unifies the headline structure
* Simplifies the instructions by using initialization scripts
* Corrects instructions for FreeBSD not to use sudo

## Changes

Updates:
* docs/Installation.md
* MANIFEST

Adds:

* share/initial-mysql.sql
* share/initial-postgres.sql

## How to test this PR

* Follow the instructions for all OSs and all database backend and make sure that testing works.

### CODE REVIEW

**Comment by pnax** [comment]
I don't get it. Are you just reverting changes made in #855, #841?

To me this is hiding essential steps in the database configuration within an obscure file, making it hard to easily configure the Backend. To make my point clear, I am against putting the `CREATE DATABASE` and `CREATE USER` instructions within a file. This is not fine in production environment because it is hiding how to define your own database/user. This might be fine to have such scripts in development environment. But then I don't think we should have them in master since it will require to keep them up to date, and we have already enough redundant things to maintain in the Backend.

I am also adding a pointer to issue #566 which is asking to avoid initializing the database with "finicky Perl one-liner". To my eyes this PR is definitely not solving this issue.

**Comment by matsduf** [comment]
> I don't get it. Are you just reverting changes made in #855, #841?

Not at all. None of the files changed in #841 are touched in this PR. It does not revert #855, but it takes a step further to make it easier to install Backend. I have for PR testing installed the databases several time and I can see that it can be done easier.

> To me this is hiding essential steps in the database configuration within an obscure file, making it hard to easily configure the Backend. To make my point clear, I am against putting the `CREATE DATABASE` and `CREATE USER` instructions within a file. This is not fine in production environment because it is hiding how to define your own database/user. This might be fine to have such scripts in development environment. But then I don't think we should have them in master since it will require to keep them up to date, and we have already enough redundant things to maintain in the Backend.

I disagree. Nothing is hidden. The file is there to be updated if you want to have another name of database, user or another password. We have had the same database name, username and password for at least 5 years, probably since the creation of Zonemster-Backend. Database name etc have to be the same in the installation instructions as in the configuration file. It is not harder to keep the sql files updated than the installation instruction file. By having the sql files there is higher chance that installation is done consistently.

> I am also adding a pointer to issue #566 which is asking to avoid initializing the database with "finicky Perl one-liner". To my eyes this PR is definitely not solving this issue.

#846 removes the need of running a script to create the database tables. Instead that is magically done by the daemon. If that PR is merged then the instruction in this PR needs minor adjustment.

**Comment by pnax** [comment]
> None of the files changed in #841 are touched in this PR

My bad, it was #834. In that PR I removed the "share/initial-mysql.sql" and "share/initial-postgresql.sql" files. These files are coming back here. Another reason why I removed them is because we cannot use them for Travis. So we had to maintain 2 different ways of creating the database. Now if they come back, the situation is back again. I really want to have less duplication within Backend.
 
>  We have had the same database name, username and password for at least 5 years, probably since the creation of Zonemster-Backend. Database name etc have to be the same in the installation instructions as in the configuration file. [...] By having the sql files there is higher chance that installation is done consistently.

Even though we agree on the end result, we don't on the path to reach it. I would like to make it possible to easily let the user adapt the database and user values. And I really think that using an SQL script is not an easy solution. Since I feel we'll continue to disagree on this point, I suggest we discuss about it during our next meeting and see if we can reach a consensus.

**Comment by matsduf** [comment]
Replaced by #882.

**Pull request closed without merging**
