### PR TITLE
Inline Ubuntu implementation of status_of_proc

### LINKED ISSUE #591: RPCAPI Status not found on CentOS7
[sandoche@vps803736 ~]$ sudo /etc/init.d/zm-rpcapi status
/etc/init.d/zm-rpcapi: line 51: status_of_proc: command not found

### PR DESCRIPTION
**Pull request by mattias-p**
Fixes #591.
Again I have only tested this on Ubuntu. I don't have a good CentOS installation to test on at the moment. Sorry about that.

### CODE REVIEW

**Comment by sandoche2k** [comment]
@mattias-p Not working on CentOS 7. I have asked @matsduf to send you information on the CentOS installation. You can try on it.

**Comment by mattias-p** [comment]
It works for me.
```sh
cd `perl -MFile::ShareDir -le 'print File::ShareDir::dist_dir("Zonemaster-Backend")'`
sh zm-rpcapi.lsb status
```
`/etc/init.d/zm-rpcapi`, however, hasn't been updated.

**Comment by sandoche2k** [comment]
> ```shell
> sh zm-rpcapi.lsb status
> ```

This works also for me. Then the installation instructions should be updated for CentOS?

**Comment by mattias-p** [comment]
If you install `zm-rpcapi.lsb` into `/etc/init.d` per the installation instruction, `/etc/init.d/zm-rpcapi status` should also work.

**Comment by sandoche2k** [comment]
`zm-rpcapi.lsb ` was installed following the  `sudo install -v -m 755 ./zm-rpcapi.lsb /etc/init.d/zm-rpcapi `
Still getting the same error:
 `
[sandoche@vps803736 Zonemaster-Backend]$ sudo /etc/init.d/zm-rpcapi start
[sandoche@vps803736 Zonemaster-Backend]$ sudo /etc/init.d/zm-testagent start
Logging to /var/log/zonemaster/zm-testagent.log
zonemaster-testagent                                          [Started]
[sandoche@vps803736 Zonemaster-Backend]$ sudo /etc/init.d/zm-rpcapi status
/etc/init.d/zm-rpcapi: line 51: status_of_proc: command not found `

**Comment by sandoche2k** [comment]
@mattias-p check the fresh installation of Centos

**Comment by mattias-p** [comment]
@sandoche2k It seems you've installed the wrong version of Backend. Make sure you have the version of zm-rpcapi.lsb from this pull request.

**Comment by sandoche2k** [comment]
I have taken the latest develop. Were your updates merged  to develop branch?

**Comment by mattias-p** [comment]
No this PR is still open. It has not been merged to develop.

**Comment by sandoche2k** [comment]
I have left information in the slack

**Pull request merged**
