### PR TITLE
Fixes issue #481 - Memory leak

### PR DESCRIPTION
**Pull request by mtoma**
Fixes the memory leak described in issue #481 
The line causing the issue is only commented out now as it was added there for a reason I can't remember.

### CODE REVIEW

**Comment by matsduf** [comment]
The line of code, commented in this PR, was introduced by zonemaster-backend#461.

**Comment by mtoma** [comment]
A follow up issue is #490 (to remove the dead code if no side effects are observed)

**Comment by sandoche2k** [comment]
@mtoma is the travis failure related to the other two issues?

**Comment by matsduf** [comment]
What fixed the memory leakage? The fix in this PR or the reset() (see #486).

**Pull request merged**
