### PR TITLE
Fixes #570 - UTF-8 issue for idn domain names

### LINKED ISSUE #570: UTF-8 issue for idn domain names
The answer for an idn domain name like café.fr comes back from the backend with a double utf8 encoding.

### PR DESCRIPTION
**Pull request by mtoma**
Issue #570.

### CODE REVIEW

**Comment by mattias-p** [comment]
I'm surprised by this approach. I have a couple of questions.

1. Is #570 specific to PostgreSQL?

2. Are we inserting strings with mixed encodings into the `test_results.params` and `test_results.results` fields? Do we have a good reason for doing so? Are we sure that we never mix encodings in a single JSON blob?

3. The documentation for [is_utf8](https://perldoc.perl.org/utf8.html#Utility-functions) and [encode_utf8](https://perldoc.perl.org/Encode.html#Basic-methods) discourages the usages seen here. Is this a rare exception to those recommendations?

**Comment by mtoma** [comment]
> I'm surprised by this approach. I have a couple of questions.
> 
> 1. Is #570 specific to PostgreSQL?
> 2. Are we inserting strings with mixed encodings into the `test_results.params` and `test_results.results` fields? Do we have a good reason for doing so? Are we sure that we never mix encodings in a single JSON blob?
> 3. The documentation for [is_utf8](https://perldoc.perl.org/utf8.html#Utility-functions) and [encode_utf8](https://perldoc.perl.org/Encode.html#Basic-methods) discourages the usages seen here. Is this a rare exception to those recommendations?

Indeed it is a rare exception because I see no other way to make one singe code work for all versions of perl and the DBD::Pg module.
The encoding you get from a select call has changed over time (not sure which are the exact DBD::Pg module versions) at one point there were coming as encoded and the encoding was to be done in the calling code with newer versions of perl the decoding was done by the module itself internally what was a problem for JSON data containing utf8 strings. It might have changed again now.
This is why I proposed the submited patch.

**Comment by matsduf** [comment]
@mtoma, could you add a short documentation in the module to explain the code? Just a few lines is enough, maybe including a reference to this PR and other sources.

**Comment by sandoche2k** [comment]
@mattias-p can you review?

**Comment by matsduf** [comment]
@mtoma, can you merge now?

**Pull request merged**
