### PR TITLE
Fix handling of nameserver option in zmb

### LINKED ISSUE #780: zmb has unexpected handling of nameserver option
For "start_domain_test" one of the options is "--nameserver DOMAIN_NAME:IP_ADDRESS". It does not say how to handle empty IP address.

Just the domain name does not work, which is the natural choice.

```sh
zmb --verbose start_domain_test --nameserver ns.nic.se --domain iis.se
{"params":{"domain":"iis.se","nameservers":[{"ip":null,"ns":"ns.nic.se"}]},"jsonrpc":"2.0","method":"start_domain_test","id":1}
{"error":{"data":"/nameservers/0/ip: Expected string - got null.","code":"-32602","message":"Invalid method parameter(s)."},"jsonrpc":"2.0","id":1}
```
You have to include the colon. It is unexpected, and should at least be doucmented.

```sh
zmb --verbose start_domain_test --nameserver ns.nic.se: --domain iis.se
{"method":"start_domain_test","params":{"nameservers":[{"ns":"ns.nic.se","ip":""}],"domain":"iis.se"},"jsonrpc":"2.0","id":1}
{"result":"9fa9d9707838f67b","id":1,"jsonrpc":"2.0"}
```

### PR DESCRIPTION
**Pull request by blacksponge**
set ip param to empty string if undefined, fix #780 

```
% ./script/zmb --verbose start_domain_test --nameserver ns.nic.se --domain iis.se
{"params":{"nameservers":[{"ip":"","ns":"ns.nic.se"}],"domain":"iis.se"},"method":"start_domain_test","jsonrpc":"2.0","id":1}
{"id":1,"result":"e3d836d48136428f","jsonrpc":"2.0"}
```

```
% ./script/zmb --verbose start_domain_test --nameserver ns.nic.se:91.226.36.45 --domain iis.se
{"id":1,"params":{"domain":"iis.se","nameservers":[{"ns":"ns.nic.se","ip":"91.226.36.45"}]},"jsonrpc":"2.0","method":"start_domain_test"}
{"id":1,"result":"dc93b829f18d2d64","jsonrpc":"2.0"}
```

### CODE REVIEW

**Review by matsduf — APPROVED** [review]

**Comment by matsduf** [comment]
Replaces #785.

**Comment by matsduf** [comment]
@mattias-p, can you review?

**Review by mattias-p — APPROVED** [review]
:+1:

**Comment by matsduf** [comment]
@blacksponge, please merge.

**Comment by pnax** [comment]
## v2021.2 testing

LGTM
no "How to test" section, used the issue to get more insights.

**Pull request merged**
