### PR TITLE
Compatibility with systemd-tmpfiles on CentOS

### LINKED ISSUE #574: Start up errors in CentOS 8 with MySQL as the backend
On running the start up 
```
sudo service zm-backend.sh start
Logging to /var/log/zonemaster/zonemaster_backend_testagent.log
zonemaster-testagent                                          [Started]
```

In /var/log/zonemaster/zm-starman-error.log" following message:
```
2019/12/30-10:12:42 Couldn't open pid file "/var/run/zonemaster/zm-starman.pid" [No such file or directory].

  at line 177 in file /usr/share/perl5/vendor_perl/Net/Server.pm
2019/12/30-10:12:42 Received QUIT. Running a graceful shutdown
2019/12/30-10:12:42 Worker processes cleaned up
2019/12/30-10:12:42 Server closing!
```
When I kill /usr/local/bin/zonemaster_backend_testagent and start the backend, I get the following:
```
[centos@ip-172-31-31-205 ~]$ sudo service zm-backend.sh startLogging to /var/log/zonemaster/zonemaster_backend_testagent.log
Use of uninitialized value $pid in numeric eq (==) at /usr/local/share/perl5/Daemon/Control.pm line 267.
Use of uninitialized value $new_pid in numeric eq (==) at /usr/local/share/perl5/Daemon/Control.pm line 270.
```
The program does not exit. But on testing the post sanity check command the backend is working and I get the correct reponse:
```
[centos@ip-172-31-31-205 ~]$ curl -H "Content-Type: application/json" -d '{"jsonrpc":"2.0","method":"version_info","id":"1"}' http://localhost:5000/ && echo
{"id":"1","jsonrpc":"2.0","result":{"zonemaster_engine":"v3.0.3","zonemaster_backend":"5.0.0"}}
```

But the remote server gets hanged. The same scenario has been repeated more than twice.

### PR DESCRIPTION
**Pull request by mattias-p**
Extends the scope of the solution in #565 to also encompass CentOS.
Fixes #574.

### CODE REVIEW

**Comment by matsduf** [comment]
@sandoche2k, this is for you to review and test.

**Comment by mattias-p** [comment]
Travis was failing for illegitimate reasons so I added an empty commit to get it on an even keel.

**Comment by mattias-p** [comment]
@sandoche2k Can you take a look at this?

**Comment by sandoche2k** [comment]
It is not clear for me the issue the current PR solves

**Comment by mattias-p** [comment]
@sandoche2k It aims to fix #574. Does it not solve the problem?

**Comment by sandoche2k** [comment]
@mattias-p I will test and get back to you

**Comment by sandoche2k** [comment]
@mattias-p 
[sandoche@vps803736 ~]$ sudo systemd-tmpfiles --create
[sandoche@vps803736 ~]$ sudo install -v -m 755 ./tmpfiles.conf /usr/lib/tmpfiles.d/zonemaster.conf
install: cannot stat './tmpfiles.conf': No such file or directory

**Comment by mattias-p** [comment]
@sandoche2k What's your current working directory? After I ran cd command at the top of the section I could see the tmpfiles.conf file.

Also, the systemd-tmpfiles command should be executed after its configuration file being installed.

**Pull request merged**
