### PR TITLE
Fix translation

### LINKED ISSUE #809: Regression on translation
Commit 8bea1174 introduced a regression on locale management as the `.UTF8` suffix is not added to the locale anymore. This cause the translation to break in all languages but the machine default language.

### PR DESCRIPTION
**Pull request by mattias-p**
## Purpose

This PR fixes a problem where translations don't work unless you have more locales installed than the ones prescribed in the installation instruction.

## Context

Fixes #809.

## Changes

This PR corrects the usage of Zonemaster::Engine::Translator->locale().

## How to test this PR

Make sure that your LANGUAGE.locale contains da_DK:
```sh
cat /etc/zonemaster/backend_config.ini
```

Make sure that the only locale listed for Danish is `da_DK.utf8`:
```sh
locale -a
```

Restart you daemons:
```sh
sudo systemctl restart zm-rpcapi zm-testagent
```

Acquire a test id:
```sh
zmtest zonemaster.net
```

Verify that you can get the results in Danish (make sure to set $TESTID or replace it with a test id that exists in the database):
```sh
zmb get_test_results --lang da --test-id $TESTID | jq -S .result.results[0]
```

### CODE REVIEW

**Comment by matsduf** [comment]
> Make sure that the only locale listed for Danish is `da_DK.utf8`:
> 
> ```shell
> locale -a
> ```

I am unsure about this requirement, and how to interpret it. Should it be the only UTF-8 locale tag or the only what so ever? Does the following meet the requirement?
```
# locale -a | grep da
da_DK.ISO8859-1
da_DK.ISO8859-15
da_DK.UTF-8
```

**Review by matsduf — APPROVED** [review]
With this PR translation works again through Backend.

**Comment by mattias-p** [comment]
> > Make sure that the only locale listed for Danish is `da_DK.utf8`:
> > ```shell
> > locale -a
> > ```
> 
> I am unsure about this requirement, and how to interpret it. Should it be the only UTF-8 locale tag or the only what so ever? Does the following meet the requirement?
> 
> ```
> # locale -a | grep da
> da_DK.ISO8859-1
> da_DK.ISO8859-15
> da_DK.UTF-8
> ```

I haven't tried with this particular configuration. But when I had a different set of additional locales installed I was unable to reproduce the bug that this PR fixes. Have you tried to reproduce the bug with your locale configuration?

**Comment by matsduf** [comment]
> I haven't tried with this particular configuration. But when I had a different set of additional locales installed I was unable to reproduce the bug that this PR fixes. Have you tried to reproduce the bug with your locale configuration?

Yes, I saw the problem all the time (after the issue was created). My default locale is sv_SE.UTF-8, and I was unable to have it in English, and there are multipel "en" in FreeBSD:
```
# locale -a | egrep "^en.*UTF-8" 
en_AU.UTF-8
en_CA.UTF-8
en_GB.UTF-8
en_HK.UTF-8
en_IE.UTF-8
en_NZ.UTF-8
en_PH.UTF-8
en_SG.UTF-8
en_US.UTF-8
en_ZA.UTF-8
```

**Comment by matsduf** [comment]
Please merge.

**Comment by mattias-p** [comment]
I've tested this v2021.2 and it LGTM.

**Pull request merged**
