### PR TITLE
Updates Changes and Backend.pm with updates for release v2021.1.3 (Backend)

### PR DESCRIPTION
**Pull request by matsduf**
## Purpose

Make the develop branch have the same content of the `Changes` file and the `Backend.pm` file as the master branch.

## Context

This PR give the same changes as 116ceb0e4aacd08983d12866858c567a4360adeb and 598fcc62fba44b4802aa1f773ee190c36f30b368, where the latter takes precedence of the former.

## Changes

Updates:
  * Changes
  * Backend.pm

### CODE REVIEW

**Comment by matsduf** [comment]
@mattias-p, @pnax and @blacksponge, can you review this? It is good to have it merged now.

**Review by blacksponge — APPROVED** [review]
it looks good to me but #839 should probably be merged first

**Comment by matsduf** [comment]
> it looks good to me but #839 should probably be merged first

They (should) touch different files, but logically I agree with you.

**Comment by pnax** [comment]
Good point, it would be nice to merge this PR after merging #839 (or at least porting the backport).

**Comment by matsduf** [comment]
@pnax, can you approve?

**Review by mattias-p — APPROVED** [review]

**Pull request merged**
